### PR TITLE
Adds descriptive text to links for accessibility

### PR DESCRIPTION
**Pull request by GlynnPhillips**
# What

Adds descriptive text to the links when the markup is not provided for the social links and therefore the component is only being used in an enhanced experience manor.

# Why 

This will improve the accessibility of this component as users of screen readers will hear what the intent of using these links will know that they open in a new window.

# Known issues 

Its worth highlighting here that this component has a "link" social option in this
component is an edge case that already behaves  in a possibly unexpected way. Clicking this option will just open the link in a new window, it doesn't do anything like copy to clipboard. For this reason this option needs its own and different descriptive text which is still not overly helpful.

# Extras

`target="_blank"` and `rel="noopener"` attributes were also added to the anchors as part of this work.

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 7.1.0 to 891f927421103dcc1794f06486df487f9b322064
js: 0.41kb increase (0.15kb/gzip)
An insignificant difference was also found for: css

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 7.1.0 to 045c03394e0f559035a76f02d466aad6b49796d8
js: 0.41kb increase (0.15kb/gzip)
An insignificant difference was also found for: css

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 7.1.0 to 2d121a1c99a9247ef32bc021108dd50a2b237167
js: 0.41kb increase (0.15kb/gzip)
An insignificant difference was also found for: css

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 7.1.0 to e5df41eb818ccc7ac6946839486e0c861faade92
js: 0.41kb increase (0.15kb/gzip)
An insignificant difference was also found for: css

**Comment by chee** [comment]
yay! thank-you, glynn!

**Pull request merged**
