### PR TITLE
Remove custom classnames

### PR DESCRIPTION
**Pull request by chee**

### CODE REVIEW

**Comment by chee** [comment]
I've also snuck a fix for #113 into this branch

**Comment by chee** [comment]
looking forward to seeing what the fox has to say about that

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 6.5.0 to 807c5b38e911b231250ba76b57ef250e3b212074
js: 0.48kb increase (0.19kb/gzip)
css: 2.73kb decrease (-0.03kb/gzip)

**Comment by chee** [comment]
yea that's right fox 2.73kb mate

**Comment by notlee** [comment]
>yea that's right fox 2.73kb mate
😂

**Comment by chee** [comment]
@notlee i'll add that to the issue as a thing that needs done, and do that in a separate PR (because there'll be a merge conflict from one of the other PRs)

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 6.5.0 to c954c6bce7310035e3e371ef415053a0d9743ddd
js: 0.7kb increase (0.24kb/gzip)
css: 4.06kb decrease (-0.11kb/gzip)

**Comment by chee** [comment]
oh there are conflicts anyway, lol

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 6.5.0 to a68fe8b37b4baf01194ad0e0831f76510796099a
js: 0.7kb increase (0.24kb/gzip)
css: 4.06kb decrease (-0.11kb/gzip)

**Pull request merged**
