### PR TITLE
Breaking

### LINKED ISSUE #142: o-share complete breaking checklist
Origami plan to release major new versions of low level components, which remove technical debt from recent additions such as component branding, and implement more recent proposals such as adding a primary Sass mixin and removing custom classes from many Sass interfaces.

**steps**

- [x] Add MIGRATION.md
- [x] Add a [primary mixin](https://github.com/Financial-Times/origami-proposals/issues/6), removing other mixins where possible.
- [x] If a mixin is required which does not output a selector, e.g. for component composition, create an [oComponentContent](https://github.com/Financial-Times/origami-proposals/issues/14#issuecomment-485815788) mixin with options like the primary mixin (`Content` infers the mixin does not output selectors).
- [x] Replace methods to customise a component's style globally with a mixin [oComponentCustomise](https://github.com/Financial-Times/origami-proposals/issues/14#issuecomment-485815788) e.g. so a whitelabel user can customise the style of a primary o-buttons button.
- [x] Replace mixins which add new variations of a component with an [oComponentAddSomething](https://github.com/Financial-Times/origami-proposals/issues/14#issuecomment-485815788) mixin e.g. so a user may output a new o-buttons button, alongside primary buttons etc.
- [x] Remove [custom classnames](https://github.com/Financial-Times/origami-proposals/issues/4).
- [x] Use the `$system-code` variable for the `source` param in image service requests, error if not found, update obt to `^ 8.2.2` locally and in circleci config.
- [x] Remove existing semver ranges e.g. for o-brand and o-icons `"o-brand": ">=2.2.0 <4",`. We can't add new features to components used with a semver range without back-porting.
- [x] Use esm consistently over cjs module syntax.
- [x] Solve existing issues labeled "breaking" if possible.

### PR DESCRIPTION
**Pull request by chee**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 6.5.0 to c7cc310f721ed0791e1cbc923dd5a4d7a5e3eb2e
js: 0.7kb increase (0.24kb/gzip)
css: 4.06kb decrease (-0.11kb/gzip)

**Comment by chee** [comment]
that's wonderful news, foxy

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 6.5.0 to 3e774ba9114a007b997f9e400b024a956e9ac2a7
js: 0.7kb increase (0.24kb/gzip)
css: 4.06kb decrease (-0.11kb/gzip)

**Comment by chee** [comment]
that's nice, foxy

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 6.5.0 to a94392a4e813096ec5d6c71f5c2291d381c14ec7
js: 0.75kb increase (0.22kb/gzip)
css: 4.05kb decrease (-0.11kb/gzip)

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 6.5.0 to 892632ab95f849e3571562e67c9d1ad745f843fd
js: 0.75kb increase (0.22kb/gzip)
css: 4.05kb decrease (-0.11kb/gzip)

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 6.5.0 to 59f1c795dc534125edefdd946b16b952da30c9a5
js: 0.72kb increase (0.21kb/gzip)
css: 4.08kb decrease (-0.12kb/gzip)

**Comment by origamiserviceuser** [comment]
o-share bundle size difference from 6.5.0 to 0fbbdb9c06dd41a850920b20914d29a2f04521d3
js: 0.72kb increase (0.21kb/gzip)
css: 4.08kb decrease (-0.12kb/gzip)

**Pull request merged**
